### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by htnlabs** [PSS1998/Binance-Trader#1]
APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.

Solution?

**Comment by PSS1998** [comment]
I haven't encountered this issue myself and it would help if you mentioned your OS, but I think adding this code before you send your request to Binance will solve your issue.
The code sets your machine's time the same as Binance server.


for linux system:

from binance.client import Client
import time
client = Client('api_key', 'api_secret')
gt = client.get_server_time()
aa = str(gt)
bb = aa.replace("{'serverTime': ","")
aa = bb.replace("}","")
gg=int(aa)
uu=gg/1000
yy=int(uu)
unix_time_as_string = yy
clk_id = time.CLOCK_REALTIME
time.clock_settime(clk_id, float(unix_time_as_string))


and incase you are using windows:

from binance.client import Client
import time
client = Client('api_key', 'api_secret')
gt = client.get_server_time()
aa = str(gt)
bb = aa.replace("{'serverTime': ","")
aa = bb.replace("}","")
gg=int(aa)
uu=gg/1000
yy=int(uu)
tt=time.localtime(yy)
win32api.SetSystemTime(tt[0],tt[1],0,tt[2],tt[3],tt[4],tt[5],0)

**Comment by htnlabs** [comment]
I am using linux server. I just cloned the repository and run. I tried to insert the code that was given to me but the error happens:

  File "/home/cabox/workspace/Binance-Trader/BinanceAPI.py", line 24, in __init__
    time.clock_settime(clk_id, float(unix_time_as_string))
PermissionError: [Errno 1] Operation not permitted

Server date:

cabox@bots-container:~/workspace/Binance-Trader$ date
Thu Apr 15 12:48:46 UTC 2021

**Comment by PSS1998** [comment]
You have to run the code with sudo privileges because of clock_settime.
Put sudo behind python when running the code.

**Comment by htnlabs** [comment]
> You have to run the code with sudo privileges because of clock_settime.
> Put sudo behind python when running the code.

Thanks
